name: geo_mapping_app
description: "App to collect road signs geo location"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  get: ^4.6.6
  quds_db: ^0.0.6+2
  flutter_adaptive_ui: ^0.8.0+1
  quds_ui_kit: ^0.0.7+10
  location: ^5.0.3
  lottie: ^2.7.0
  local_hero: ^0.3.0
  hero_animation: ^1.1.4
  flutter_animate: ^4.4.0
  animate_do: ^3.1.2
  flutter_native_splash: ^2.3.9
  rename_app_plus: ^1.2.1
  device_preview: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  animated_text_kit: ^4.2.2
  animated_notch_bottom_bar: ^1.0.1
  file_selector: ^1.0.2
  excel: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: "assets/images/govt_logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/govt_logo.png"
    ios:
      enable: true
      image_path: "assets/images/govt_logo.png"
    web:
      enable: true
      fav_icon: "assets/images/govt_logo.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/lotties/